### ISSUE TITLE
Option '--livereload' not recognized (ignoring).

### ISSUE THREAD

**Issue by TrySpace** [axemclion/cordova-plugin-browsersync#2]
I get:

     Option '--livereload' not recognized (ignoring).

When adding it as a plugin, (following the 2 steps) I also tried the the project hook but its not executing after prepare either.

I would like to try the third option, but there's no examples yet. Should I run changeHost.js in my main script or somewhere else? And do I need the browserSyncServer.js perse?

It would be great if I could just point it to my already running `gulp watch` which runs browsersync, it just doesn't have access to the cordova.js and its plugins. If somehow I could automate the prepare process and reload the res/www directory...

**Comment by axemclion** [comment]
It is actually `-- --live-reload`. Note the double `-- --`. This is required sine just having a `--` is not passed by Cordova down to the plugins. 

I am working on a blog post with examples to make the third option more explicit. I am guessing that this option could be the most popular.

**Comment by axemclion** [comment]
@TrySpace Do you have an example of your gulp script with browserwatch ? I could build my example from that.

**Comment by axemclion** [comment]
Closing due to lack of response. Please reopen this issue if needed.
