### ISSUE TITLE
Files not being watch when --ignore not passed, no fixed on npm, but fixed in git

### ISSUE THREAD

**Issue by csantanapr** [axemclion/cordova-plugin-browsersync#3]
Problem is fixed in copy in git but the code published on npm is different.

on NPM 0.0.3
```
bs.watch(www + '/**/*.*', {
        ignored: www + '/' + opts.ignore
    }, function(event, files) {
```

when opts.ignore is undefined watch doesn't work,
code in git repo is fixed, just need to upload to npm

```
bs.watch(www + '**/*.*', opts.ignore ? {
        ignored: www + '/' + opts.ignore
    } : {}, function(event, files) {
```

**Comment by axemclion** [comment]
Fixed in 9e20d4cd74da017f509b2cba0a90258d511a5c57. Also pushed to npm.
